---
- name: install influxdb key
  become: yes
  become_user: root
  apt_key: >
    url={{influxdb_key}}
    state=present
  register: influxdb_key_added

- name: add influxdb apt-get list
  become: yes
  become_user: root
  with_items:
    - etc/apt/sources.list.d/influxdb.list
  template: >-
    src={{item}}.j2
    dest=/{{item}}
    mode=0644
  register: influxdb_source_added
    
- name: apt-get update
  become: yes
  become_user: root
  when: influxdb_key_added|changed or influxdb_source_added|changed
  apt: update=yes

