---
- include_role:
    name: andrewrothstein.unarchivedeps
- name: checking for installation at {{ influxdb_install_dir }}
  become: true
  become_user: root
  stat:
    path: '{{ influxdb_install_dir }}'
  changed_when: false
  register: influxdb_binary
- when: not influxdb_binary.stat.exists
  block:
    - name: downloading {{ influxdb_tgz_url }} to {{ influxdb_tmp_tgz }}
      become: true
      become_user: root
      get_url:
        url: '{{ influxdb_tgz_url }}'
        dest: '{{ influxdb_tmp_tgz }}'
        checksum: '{{ influxdb_checksum }}'
        mode: 0644
    - name: unarchiving {{ influxdb_tmp_tgz }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ influxdb_tmp_tgz }}'
        dest: '{{ influxdb_install_parent_dir }}'
        creates: '{{ influxdb_install_dir }}'
  always:
    - name: rm {{ influxdb_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ influxdb_tmp_tgz }}'
        state: absent
- name: linking {{ influxdb_link_dir }} to {{ influxdb_install_dir }}
  become: true
  become_user: root
  file:
    src: '{{ influxdb_install_dir }}'
    dest: '{{ influxdb_link_dir }}'
    state: link

- name: add to default profile.d
  become: true
  become_user: root
  with_items:
    - f: influxdb.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'
- when: influxdb_config is defined
  include_tasks: configure.yml
