---
# tasks file for ansible-influxdb

- name: Debian install
  when: ansible_os_family == 'Debian'
  include: Debian.yml

- name: RedHat install
  when: ansible_os_family == 'RedHat'
  include: RedHat.yml

- name: install package...
  package: name=influxdb state=present

