---
- name: Debian install
  when: ansible_os_family == 'Debian'
  include: Debian.yml

- name: RedHat install
  when: ansible_os_family == 'RedHat'
  include: RedHat.yml

- name: install package...
  become: yes
  become_user: root
  with_items:
    - influxdb
  package: >
    name={{item}}
    state=present
